### ISSUE TITLE
Possible mistake in session2 - challenge 3

### ISSUE THREAD

**Issue by tomcoakes** [jordanpoulton/ruby_kickstart#18]
The instructions in the comment of this file state:

"Write a method named every_other_char for strings that,
returns an array containing every other character"

However, the tests are looking for a string to be returned rather than an array (as illustrated in the example immediately below).

Is this a mistake? Not a big thing, but it did cause me some confusion for a short while!

**Comment by jordanpoulton** [comment]
Good spot @tomcoakes - it should be a string. Amended.
